### ISSUE TITLE
Move CommonSettings into per-bastion-type config

### ISSUE THREAD

**Issue by ProgrammerDan** [DevotedMC/Bastion#40]
So, it would be best to add /ctr prevention to per-bastion-type config, so that it can be enabled or disabled as appropriate. For instance, Claims bastions in Devoted's setup require direct destruction (they don't block placement of blocks) so it wouldn't make sense for them to block /ctr use, when they don't block /ctf use. Since at present it's a global setting, this makes it hard for me to turn it on at all.

Thoughts? Have I misunderstood?

**Comment by Aleksey-Terzi** [comment]
Not sure this should be per-bastion-type - this option defines common behavior.
If bastion prevents placing blocks and setting is enabled - then bastion should also prevent reinforcing/changing group as well.
If this is Claims bastion - then this setting shouldn't prevent reinforcing.

I didn't test this with Claims bastion, but should work since I'm using common function: https://github.com/DevotedMC/Bastion/blob/master/src/main/java/isaac/bastion/listeners/BastionInteractListener.java#L158

But I will test this later today on Devoted test server to be 100% sure.

PS. Maybe name of setting is not very good describing purpose of it, but not sure what name could be better

**Comment by ProgrammerDan** [comment]
Closing on report / test results. Thanks!
